# Generated by Django 4.0.10 on 2023-10-29 10:17

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=app.models.create_id, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('status', models.IntegerField(choices=[(0, '未着手'), (1, '進行中'), (2, '一時中断'), (3, '中止'), (4, '完了')], verbose_name='ステータス')),
                ('deadline', models.DateTimeField(verbose_name='期限')),
                ('description', models.TextField(max_length=255, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
